# -*- coding: utf-8 -*-

CELL_SIZE = 50
SCREEN_SIZE = (750, 900)
MAP_SIZE = (750, 750)
BLACK = (0, 0, 0)
LANE_CELL = 'L'
WALL_CELL = 'W'
START_CELL = 'S'
EXIT_CELL = 'E'
HERO_CELL = 'H'
ITEM_CELL = 'I'
